ALTER TABLE "AdminSession" ADD COLUMN IF NOT EXISTS "twoFactorVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AdminSession" ADD COLUMN IF NOT EXISTS "otpHash" TEXT;
ALTER TABLE "AdminSession" ADD COLUMN IF NOT EXISTS "otpExpiresAt" TIMESTAMP(3);
